Rails.application.routes.draw do
  get 'message/show'
  get 'usergroup/create'
  get 'bookmovie/new'
  get 'bookmovie/create'
  get 'group/new'
  get 'group/create'
  get 'group/show'
  get 'usergroup/show'
  get 'usergroup/approve'
  get 'usergroup/reject'
  post 'usergroup/approve' =>'usergroup#approve'
  patch 'usergroup/approve' =>'usergroup#approve'
  post 'usergroup/reject' =>'usergroup#reject'
  patch 'usergroup/reject' =>'usergroup#reject'
  get 'movie/new'
  get 'movie/create'
  get 'movie/show'
  get 'movie/book'
  post 'movie/book'=>'movie#book'
  get 'user/show'
  get 'user/create'
  get 'main/login'=>'main#login'
  post 'main/login'=>'main#login'
  get 'session/new'
  get 'session/create'
  get 'session/destroy'
  delete 'session/destroy'
  post 'group/join'
  get 'group/join'
  get 'user/create_user'
  post 'user/create_user'
 # get 'user/save_user'
  post 'user/save_user'
   #get 'movie/three'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'main#login'

end
